nameSuffix: -prod

bases:
- ../../base

patches:
- path: cert.yaml
  target:
    group: networking.gke.io
    version: v1beta1
    kind: ManagedCertificate
    name: klaraworks-cert

- path: ingress.yaml
  target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: klaraworks-ingress

- path: deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: klaraworks-deployment
