id: 20200215-hamakaze
type: Picture
meta:
- - Japanese
  - title: 対空戦だけじゃ、つまらないしね
    origin: 艦隊これくしょん
- - English
  - title: Just fighting anti-air battles is boring right.
    origin: Kantai Collection

